# Rename and Combine

## Import Libraries

In [1]:
import pandas as pd

## Import Dataset

In [2]:
dataset = pd.read_csv("./datasets/chickweight.csv")

## Rename
`dataframe.rename()` allows you to rename indexes and columns

In [6]:
dataset.rename(columns=dict(zip(dataset.columns, dataset.columns.str.lower())))

     weight  time  chick  diet
0        42     0      1     1
1        51     2      1     1
2        59     4      1     1
3        64     6      1     1
4        76     8      1     1
..      ...   ...    ...   ...
573     175    14     50     4
574     205    16     50     4
575     234    18     50     4
576     264    20     50     4
577     264    21     50     4

[578 rows x 4 columns]

In [7]:
dataset.rename(index={ 0: "First Entry" })

             weight  Time  Chick  Diet
First Entry      42     0      1     1
1                51     2      1     1
2                59     4      1     1
3                64     6      1     1
4                76     8      1     1
...             ...   ...    ...   ...
573             175    14     50     4
574             205    16     50     4
575             234    18     50     4
576             264    20     50     4
577             264    21     50     4

[578 rows x 4 columns]

Most of the time you"ll be renaming columns & rows rather than individual indexes

In [13]:
dataset.rename_axis("chickens", axis="rows").rename_axis("features", axis="columns")

features  weight  Time  Chick  Diet
chickens
0             42     0      1     1
1             51     2      1     1
2             59     4      1     1
3             64     6      1     1
4             76     8      1     1
...          ...   ...    ...   ...
573          175    14     50     4
574          205    16     50     4
575          234    18     50     4
576          264    20     50     4
577          264    21     50     4

[578 rows x 4 columns]

## Combine

In [11]:
ca_videos = pd.read_csv("./datasets/videos/CAvideos.csv")
de_videos = pd.read_csv("./datasets/videos/DEvideos.csv")

pd.concat([ ca_videos, de_videos ]).head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [12]:
left = ca_videos.set_index(["title", "trending_date"])
right = de_videos.set_index(["title", "trending_date"])

left.join(right, lsuffix="_CAN", rsuffix="_UK").head()

                                                                 video_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       EXEaMjFeiEk
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       bYvQmusLaxw
                                                   17.21.12       bYvQmusLaxw

                                                                     channel_title_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                 Markiplier
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03             AlexRamiGaming
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03             AlexRamiGaming
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       Pure Living for Life
                                                   17.21.12       Pure Living for Life

                                                                  category_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    20
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    24
                                                   17.21.12                    24

                                                                          publish_time_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       2018-03-10T06:26:17.000Z
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       2017-12-20T02:49:11.000Z
                                                   17.21.12       2017-12-20T02:49:11.000Z

                                                                                                           tags_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       timber frame|"timber framing"|"timber frame ra...
                                                   17.21.12       timber frame|"timber framing"|"timber frame ra...

                                                                  views_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03          200764
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           79152
                                                   17.21.12          232762

                                                                  likes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           47058
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            5199
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            5620
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            7761
                                                   17.21.12           15515

                                                                  dislikes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01               1023
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                542
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                537
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                159
                                                   17.21.12                329

                                                                  comment_count_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    8250
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      11
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      45
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    1965
                                                   17.21.12                    3601

                                                                                              thumbnail_link_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       https://i.ytimg.com/vi/DvPW66IFhMI/default.jpg
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       https://i.ytimg.com/vi/EXEaMjFeiEk/default.jpg
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
                                                   17.21.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg

                                                                  ...  \
title                                              trending_date  ...
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       ...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       ...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       ...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       ...
                                                   17.21.12       ...

                                                                                                            tags_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                                                     NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                                                     NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                                                     NaN
                                                   17.21.12                                                     NaN

                                                                  views_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       835930.0
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN

                                                                  likes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01        47058.0
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN

                                                                 dislikes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           1023.0
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03              NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03              NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12              NaN
                                                   17.21.12              NaN

                                                                 comment_count_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                8250.0
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                   NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                   NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                   NaN
                                                   17.21.12                   NaN

                                                                                               thumbnail_link_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                                                  NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                                                  NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                                                  NaN
                                                   17.21.12                                                  NaN

                                                                  comments_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                      False
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                        NaN
                                                   17.21.12                        NaN

                                                                 ratings_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    False
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                      NaN
                                                   17.21.12                      NaN

                                                                 video_error_or_removed_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                          False
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                            NaN
                                                   17.21.12                            NaN

                                                                                                     description_UK
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       Getting Over It continues with RAGE BEYOND ALL...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                                                     NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                                                     NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                                                     NaN
                                                   17.21.12                                                     NaN

[5 rows x 28 columns]